#!/bin/bash
#variable
b='\033[34;1m'
g='\033[32;1m'
p='\033[35;1m'
c='\033[36;1m'
r='\033[31;1m'
w='\033[37;1m'
y='\033[33;1m'

isi(){
     url=http://ip-api.com/
     echo $y"masukkan ip mantan"
     read ip
     curl -s $url$ip
     echo $y"terima kasih kerana guna tools Gadenia"
}

perintah(){
    echo $y"nick lu :"
    read nick
    echo $y"mau apa $nick"
    echo "mau teruskan?"
    read -p "y/n :" pill
    if [ $pill = "y" ];then
         clear
         banner
         isi
    else 
         echo $r"salah anjing"
         exit
    fi
}

banner(){
   echo $b"-----------------------------------"
   sleep 1
   echo $y"author : MrGardenia"
   sleep 1
   echo $y"email :mr.gardeniagaming@gmail.com"
   sleep 1
   echo $b"-----------------------------------"
   sleep 1
   echo""
}
perintah
